// <auto-generated />
using BackEnd_Simple_CRUD_in_C_SHARP_MySQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd_Simple_CRUD_in_C_SHARP_MySQL.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BackEnd_Simple_CRUD_in_C_SHARP_MySQL.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Ocupation")
                        .HasColumnType("longtext")
                        .HasColumnName("ocupation");

                    b.HasKey("Id");

                    b.ToTable("tb_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gabrielle Pereira",
                            Ocupation = "Terapeuta respiratório registrado"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Emily Gonçalves",
                            Ocupation = "funcionária do correio"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lavínia Pereira",
                            Ocupation = "enfermeira do hospício"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Raissa Alves",
                            Ocupation = "diretora de tecnologia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Isabelle Cardoso",
                            Ocupation = "Técnico de pré-impressão eletrônica"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fernanda Castro",
                            Ocupation = "Mecânica de veículos pesados e equipamentos móveis"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Matheus Goncalves",
                            Ocupation = "terapeuta de radiação"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kauan Correia",
                            Ocupation = "Instalador de aquecimento, ar condicionado e refrigeração"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Otávio Carvalho",
                            Ocupation = "Trabalhador de navio de cruzeiro"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Carlos Ferreira",
                            Ocupation = "Assistente médico"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
